// Generated by CoffeeScript 1.9.1
(function() {
  var Block, Dirt, Entity, Gravel, Ladder, Level, Ninja, Player, Rock, Treasure, gfx, keys, levels, utils,
    slice = [].slice,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  utils = {
    now: function() {
      return new Date().getTime();
    },
    snap: function(value, snapSize) {
      return Math.floor(value / snapSize) * snapSize;
    },
    rand: function(min, max) {
      var range;
      if (max == null) {
        max = min;
        min = 0;
      }
      range = max - min;
      return Math.floor((Math.random() * range) + min);
    }
  };

  gfx = {
    tileW: 24,
    tileH: 24,
    init: function() {
      var canvas;
      canvas = document.querySelector("#game");
      this.ctx = canvas != null ? typeof canvas.getContext === "function" ? canvas.getContext("2d") : void 0 : void 0;
      if (!this.ctx) {
        return false;
      }
      this.w = canvas.width;
      this.h = canvas.height;
      return true;
    },
    clear: function() {
      return this.ctx.clearRect(0, 0, this.w, this.h);
    },
    load: function(onload) {
      this.sprites = new Image();
      this.sprites.src = "resources/sprites.png";
      return this.sprites.onload = function() {
        return onload();
      };
    },
    drawSprite: function(col, row, x, y, w, h, scale) {
      if (w == null) {
        w = 1;
      }
      if (h == null) {
        h = 1;
      }
      if (scale == null) {
        scale = 1;
      }
      w *= this.tileW;
      h *= this.tileH;
      return this.ctx.drawImage(this.sprites, col * w, row * h, w, h, x, y, w * scale, h * scale);
    }
  };

  keys = {
    up: false,
    down: false,
    left: false,
    right: false,
    space: false,
    reset: function() {
      return this.up = this.down = this.left = this.right = this.space = false;
    },
    trigger: function(keyCode, isDown) {
      switch (keyCode) {
        case 37:
          return this.left = isDown;
        case 39:
          return this.right = isDown;
        case 38:
          return this.up = isDown;
        case 40:
          return this.down = isDown;
        case 32:
          if (isDown) {
            console.log("FIRE AWAY!");
          }
          return this.space = isDown;
      }
    }
  };

  document.addEventListener("keydown", function(e) {
    return keys.trigger(e.keyCode, true);
  }, false);

  document.addEventListener("keyup", function(e) {
    return keys.trigger(e.keyCode, false);
  }, false);

  Level = (function() {
    Level.prototype.w = 0;

    Level.prototype.h = 0;

    Level.prototype.treasures = 0;

    Level.prototype.ninjas = [];

    function Level(level, game1) {
      this.game = game1;
      this.load(level);
    }

    Level.prototype.load = function(level) {
      var asciiMap, col, row, x, y;
      this.ninjas = [];
      this.treasures = 0;
      asciiMap = (function() {
        var i, len, ref, results;
        ref = level.data.split("\n");
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          row = ref[i];
          results.push(row.split(""));
        }
        return results;
      })();
      this.map = (function() {
        var i, len, results;
        results = [];
        for (y = i = 0, len = asciiMap.length; i < len; y = ++i) {
          row = asciiMap[y];
          results.push((function() {
            var j, len1, results1;
            results1 = [];
            for (x = j = 0, len1 = row.length; j < len1; x = ++j) {
              col = row[x];
              switch (col) {
                case "@":
                  results1.push(new Dirt());
                  break;
                case "O":
                  results1.push(new Rock());
                  break;
                case "P":
                  this.addPlayer(x, y);
                  results1.push(new Block());
                  break;
                case "X":
                  this.addNinja(x, y);
                  results1.push(new Block());
                  break;
                case "*":
                  this.treasures++;
                  results1.push(new Treasure());
                  break;
                case "#":
                  results1.push(new Ladder());
                  break;
                case "-":
                  results1.push(new Ladder(true));
                  break;
                default:
                  results1.push(new Block());
              }
            }
            return results1;
          }).call(this));
        }
        return results;
      }).call(this);
      this.h = this.map.length;
      return this.w = this.map[0].length;
    };

    Level.prototype.addNinja = function(x, y) {
      var ninja, xPos, yPos;
      xPos = x * gfx.tileW;
      yPos = y * gfx.tileH;
      ninja = new Ninja(this, xPos, yPos);
      return this.ninjas.push(ninja);
    };

    Level.prototype.addPlayer = function(x, y) {
      return this.game.setPlayer(x * gfx.tileW, y * gfx.tileH, this);
    };

    Level.prototype.removeBlock = function(x, y, block) {
      this.map[y][x] = new Block();
      if (block.constructor === Treasure) {
        if (--this.treasures === 0) {
          alert("Level Complete!");
          return game.reset();
        }
      }
    };

    Level.prototype.getBlockIndex = function(x, y) {
      return [Math.floor(x / gfx.tileW), Math.floor(y / gfx.tileH)];
    };

    Level.prototype.getBlockEdge = function(position, forVertical) {
      var snapTo;
      if (forVertical == null) {
        forVertical = false;
      }
      snapTo = !forVertical ? gfx.tileW : gfx.tileH;
      return utils.snap(position, snapTo);
    };

    Level.prototype.getBlock = function(x, y) {
      var ref, ref1, xBlock, yBlock;
      ref = this.getBlockIndex(x, y), xBlock = ref[0], yBlock = ref[1];
      return ((ref1 = this.map[yBlock]) != null ? ref1[xBlock] : void 0) || new Rock();
    };

    Level.prototype.getBlocks = function() {
      var coords, i, len, ref, results, x, y;
      coords = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      results = [];
      for (i = 0, len = coords.length; i < len; i++) {
        ref = coords[i], x = ref[0], y = ref[1];
        results.push(this.getBlock(x, y));
      }
      return results;
    };

    Level.prototype.update = function() {
      var block, i, j, k, l, len, len1, len2, len3, ninjas, ref, ref1, ref2, results, row, x, y;
      ref = this.map;
      for (y = i = 0, len = ref.length; i < len; y = ++i) {
        row = ref[y];
        for (x = j = 0, len1 = row.length; j < len1; x = ++j) {
          block = row[x];
          block.update(x, y, this);
        }
      }
      ref1 = this.ninjas;
      for (k = 0, len2 = ref1.length; k < len2; k++) {
        ninjas = ref1[k];
        ninjas.update();
      }
      ref2 = this.ninjas;
      results = [];
      for (l = 0, len3 = ref2.length; l < len3; l++) {
        ninjas = ref2[l];
        results.push(this.checkCollision(this.game.player, ninjas));
      }
      return results;
    };

    Level.prototype.checkCollision = function(p, b) {
      if (p.x + p.w >= b.x && p.x <= b.x + b.w && p.y + p.h >= b.y && p.y <= b.y + b.h) {
        alert("You dead, mon.");
        return game.reset();
      }
    };

    Level.prototype.render = function(gfx) {
      var block, i, j, k, len, len1, len2, ninjas, ref, ref1, results, row, x, y;
      ref = this.map;
      for (y = i = 0, len = ref.length; i < len; y = ++i) {
        row = ref[y];
        for (x = j = 0, len1 = row.length; j < len1; x = ++j) {
          block = row[x];
          block.render(gfx, x * gfx.tileW, y * gfx.tileH);
        }
      }
      ref1 = this.ninjas;
      results = [];
      for (k = 0, len2 = ref1.length; k < len2; k++) {
        ninjas = ref1[k];
        results.push(ninjas.render(gfx));
      }
      return results;
    };

    Level.prototype.digAt = function(dir, x, y) {
      var block, ref, xb, yb;
      ref = this.getBlockIndex(x, y), xb = ref[0], yb = ref[1];
      xb = xb + (dir === "RIGHT" ? 1 : -1);
      if (yb + 1 > this.h || xb < 0 || xb > this.w - 1) {
        return;
      }
      block = this.map[yb + 1][xb];
      if (block.digIt != null) {
        block.digIt();
      }
      if (block.constructor === Block) {
        return this.map[yb + 1][xb] = new Gravel();
      }
    };

    return Level;

  })();

  levels = [
    {
      name: "DIG and BUILD",
      data: ".P................X.....\n@-@@.........@@@@@@@-@..\n.#..@@@.............#...\n.#.....@@.@@.....X..#...\n@OO#.........#@@...O#..^\n...#.........#......#.^O\n...#..@@-@@@@#..-@@@@@OO\n...#....#....#..#.......\n...#....#....#..#.......\n...#....#....#..#.......\n@-@@OOOOO.#.@@@@@#@@-@@@\n.#.X......#......#..#...\n.#...*....#......#..#...\n####..@@#@@..-@@@@@@@..*\n####....#....#.........#\n####....#....#.........#\nOOOOOOOOOOOOOOOOOOOOOOOO"
    }
  ];

  Entity = (function() {
    Entity.prototype.x = 0;

    Entity.prototype.y = 0;

    Entity.prototype.w = 18;

    Entity.prototype.h = 24;

    Entity.prototype.speed = 4;

    Entity.prototype.dir = "LEFT";

    function Entity(level1, x1, y1) {
      this.level = level1;
      this.x = x1;
      this.y = y1;
      this.falling = true;
      this.wasFalling = true;
      this.onLadder = false;
      this.wasOnLadder = false;
      this.onTopOfLadder = false;
    }

    Entity.prototype.update = function() {};

    Entity.prototype.render = function(gfx) {
      return gfx.ctx.fillText("?", this.x, this.y);
    };

    Entity.prototype.move = function(x, y) {
      var bl, br, ref, ref1, tl, tr, xo, xv, yo, yv;
      if (this.falling) {
        y += this.speed * 2;
      }
      this.wasFalling = this.falling;
      xo = x;
      yo = y;
      xv = this.x + xo;
      yv = this.y + yo;
      ref = this.level.getBlocks([this.x, yv], [this.x, yv + (this.h - 1)], [this.x + (this.w - 1), yv], [this.x + (this.w - 1), yv + (this.h - 1)]), tl = ref[0], bl = ref[1], tr = ref[2], br = ref[3];
      if (y < 0 && (tl.solid || tr.solid)) {
        yo = this.level.getBlockEdge(this.y, "VERT") - this.y;
      }
      if (y > 0 && (bl.solid || br.solid)) {
        yo = this.level.getBlockEdge(yv + (this.h - 1), "VERT") - this.y - this.h;
        this.falling = false;
      }
      ref1 = this.level.getBlocks([xv, this.y], [xv, this.y + (this.h - 1)], [xv + (this.w - 1), this.y], [xv + (this.w - 1), this.y + (this.h - 1)]), tl = ref1[0], bl = ref1[1], tr = ref1[2], br = ref1[3];
      if (x < 0 && (tl.solid || bl.solid)) {
        xo = this.level.getBlockEdge(this.x) - this.x;
      }
      if (x > 0 && (tr.solid || br.solid)) {
        xo = this.level.getBlockEdge(xv + (this.w - 1)) - this.x - this.w;
      }
      this.x += xo;
      this.y += yo;
      return this.checkNewPos(x, y);
    };

    Entity.prototype.checkNewPos = function(origX, origY) {
      var bl, block, br, i, len, nearBlocks, ref, snapAmount, tl, touchingALadder, tr;
      this.wasOnLadder = this.onLadder;
      nearBlocks = (ref = this.level.getBlocks([this.x, this.y], [this.x, this.y + this.h], [this.x + (this.w - 1), this.y], [this.x + (this.w - 1), this.y + this.h]), tl = ref[0], bl = ref[1], tr = ref[2], br = ref[3], ref);
      for (i = 0, len = nearBlocks.length; i < len; i++) {
        block = nearBlocks[i];
        if (block.touchable) {
          block.touch(this);
        }
      }
      this.onLadder = false;
      touchingALadder = nearBlocks.some(function(block) {
        return block.climbable;
      });
      if (touchingALadder) {
        this.onLadder = true;
        this.falling = false;
        if (origY !== 0) {
          snapAmount = utils.snap(this.x, gfx.tileW);
          if (!(bl.climbable || tl.climbable)) {
            this.x = snapAmount + gfx.tileW;
          }
          if (!(br.climbable || tr.climbable)) {
            this.x = snapAmount;
          }
        }
      }
      this.onTopOfLadder = this.onLadder && !(tl.climbable || tr.climbable) && (this.y + this.h) % gfx.tileH === 0;
      if (!this.onLadder && !this.falling) {
        if (!(bl.solid || br.solid || bl.climbable || br.climbable)) {
          return this.falling = true;
        }
      }
    };

    return Entity;

  })();

  Player = (function(superClass) {
    extend(Player, superClass);

    function Player() {
      Player.__super__.constructor.apply(this, arguments);
      this.dir = "RIGHT";
    }

    Player.prototype.update = function() {
      var xo, yo;
      xo = yo = 0;
      if (!this.falling) {
        if (keys.left) {
          xo -= this.speed;
          this.dir = "LEFT";
        }
        if (keys.right) {
          xo += this.speed;
          this.dir = "RIGHT";
        }
      }
      if (keys.down && this.onLadder) {
        yo += this.speed;
      }
      if (keys.up && this.onLadder && !this.onTopOfLadder) {
        yo -= this.speed;
      }
      if (keys.space) {
        this.dig();
      }
      return this.move(xo, yo);
    };

    Player.prototype.render = function(gfx) {
      return gfx.drawSprite(0, 0, this.x, this.y);
    };

    Player.prototype.dig = function() {
      if (utils.now() - this.lastDig < (6 * 1000)) {
        return;
      }
      this.level.digAt(this.dir, this.x, this.y);
      return this.lastDig = utils.now();
    };

    return Player;

  })(Entity);

  Ninja = (function(superClass) {
    extend(Ninja, superClass);

    function Ninja() {
      return Ninja.__super__.constructor.apply(this, arguments);
    }

    Ninja.prototype.render = function(gfx) {
      return gfx.drawSprite(0, 1, this.x, this.y);
    };

    return Ninja;

  })(Entity);

  Block = (function() {
    Block.prototype.touchable = false;

    Block.prototype.solid = false;

    Block.prototype.climbable = false;

    function Block() {}

    Block.prototype.update = function() {};

    Block.prototype.render = function(gfx, x, y) {};

    return Block;

  })();

  Dirt = (function(superClass) {
    extend(Dirt, superClass);

    function Dirt() {
      return Dirt.__super__.constructor.apply(this, arguments);
    }

    Dirt.prototype.solid = true;

    Dirt.prototype.render = function(gfx, x, y) {
      var oldAlpha;
      oldAlpha = gfx.ctx.globalAlpha;
      gfx.ctx.globalAlpha = 1 - this.digTime / 80;
      gfx.drawSprite(4, 1, x, y);
      return gfx.ctx.globalAlpha = oldAlpha;
    };

    Dirt.prototype.digIt = function() {
      this.digTime = 80;
      return this.solid = false;
    };

    Dirt.prototype.update = function() {
      if (--this.digTime === 50) {
        return this.solid = true;
      }
    };

    return Dirt;

  })(Block);

  Rock = (function(superClass) {
    extend(Rock, superClass);

    function Rock() {
      return Rock.__super__.constructor.apply(this, arguments);
    }

    Rock.prototype.solid = true;

    Rock.prototype.render = function(gfx, x, y) {
      return gfx.drawSprite(4, 0, x, y);
    };

    return Rock;

  })(Block);

  Treasure = (function(superClass) {
    extend(Treasure, superClass);

    Treasure.prototype.touchable = true;

    Treasure.prototype.colleced = false;

    function Treasure() {
      this.yOff = Math.random() * Math.PI;
    }

    Treasure.prototype.touch = function(entity) {
      if (entity.constructor === Player) {
        return this.collected = true;
      }
    };

    Treasure.prototype.update = function(x, y, level) {
      this.yOff += Math.PI / 24;
      if (this.collected) {
        return level.removeBlock(x, y, this);
      }
    };

    Treasure.prototype.render = function(gfx, x, y) {
      var ySine;
      ySine = Math.floor(Math.sin(this.yOff) * 4);
      return gfx.drawSprite(5, 1, x, y + ySine);
    };

    return Treasure;

  })(Block);

  Ladder = (function(superClass) {
    extend(Ladder, superClass);

    Ladder.prototype.climbable = true;

    function Ladder(top1) {
      this.top = top1;
      this.frame = top ? 6 : 5;
    }

    Ladder.prototype.render = function(gfx, x, y) {
      return gfx.drawSprite(5, 0, x, y);
    };

    return Ladder;

  })(Block);

  Gravel = (function(superClass) {
    extend(Gravel, superClass);

    function Gravel() {
      return Gravel.__super__.constructor.apply(this, arguments);
    }

    Gravel.prototype.solid = true;

    Gravel.prototype.digTime = 100;

    Gravel.prototype.update = function(x, y, level) {
      if (--this.digTime < 0) {
        return level.removeBlock(x, y, this);
      }
    };

    Gravel.prototype.render = function(gfx, x, y) {
      var oldAlpha;
      oldAlpha = gfx.ctx.globalAlpha;
      gfx.ctx.globalAlpha = this.digTime / 50;
      gfx.drawSprite(4, 2, x, y);
      return gfx.ctx.globalAlpha = oldAlpha;
    };

    return Gravel;

  })(Block);

  this.game = {
    init: function() {
      if (!gfx.init()) {
        alert("Could not set up game canvas!");
        return;
      }
      return gfx.load(function() {
        return game.reset();
      });
    },
    stop: function() {
      return this.running = false;
    },
    start: function() {
      return this.running = true;
    },
    reset: function() {
      this.player = new Player;
      this.level = new Level(levels[0], this);
      keys.reset();
      if (!this.running) {
        this.start();
        return this.tick();
      }
    },
    setPlayer: function(x, y, level) {
      this.player.level = level;
      this.player.x = x;
      return this.player.y = y;
    },
    tick: function() {
      if (!this.running) {
        return;
      }
      gfx.clear();
      this.update();
      this.render();
      return setTimeout((function() {
        return game.tick();
      }), 33);
    },
    update: function() {
      this.level.update();
      return this.player.update();
    },
    render: function() {
      this.level.render(gfx);
      return this.player.render(gfx);
    }
  };

}).call(this);
